import { Participation, ParticipationType } from '../types';
import { generateUUID, calculatePartDate } from './utils';

const rawParticipations = [
  // SEMANA 27 DE OUT– 2 DE NOV | 2025
  { publisherName: 'Edmardo Queiroz', week: '27 de OUT - 2 de NOV, 2025', partTitle: 'Presidente', type: ParticipationType.PRESIDENTE },
  { publisherName: 'Edmardo Queiroz', week: '27 de OUT - 2 de NOV, 2025', partTitle: 'Oração Inicial', type: ParticipationType.ORACAO_INICIAL },
  { publisherName: 'Marcos Rogério', week: '27 de OUT - 2 de NOV, 2025', partTitle: 'Tenha uma vida feliz e saudável', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Emerson Souza', week: '27 de OUT - 2 de NOV, 2025', partTitle: 'Joias espirituais', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Gustavo Rangel', week: '27 de OUT - 2 de NOV, 2025', partTitle: 'Leitura da Bíblia', type: ParticipationType.TESOUROS, duration: 4 },
  { publisherName: 'Mylena Balieira', week: '27 de OUT - 2 de NOV, 2025', partTitle: 'Cultivando o interesse', type: ParticipationType.MINISTERIO, duration: 3 },
  { publisherName: 'Larissa Queiroz', week: '27 de OUT - 2 de NOV, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Isabelle Cruz Silva', week: '27 de OUT - 2 de NOV, 2025', partTitle: 'Cultivando o interesse', type: ParticipationType.MINISTERIO, duration: 4 },
  { publisherName: 'Érika Segall', week: '27 de OUT - 2 de NOV, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Fernando Balieira', week: '27 de OUT - 2 de NOV, 2025', partTitle: 'Discurso', type: ParticipationType.MINISTERIO, duration: 5 },
  { publisherName: 'Israel Vieira', week: '27 de OUT - 2 de NOV, 2025', partTitle: 'Recapitulação do Programa do Congresso', type: ParticipationType.VIDA_CRISTA, duration: 15 },
  { publisherName: 'Marcos Vinícios', week: '27 de OUT - 2 de NOV, 2025', partTitle: 'Dirigente', type: ParticipationType.DIRIGENTE, duration: 30 },
  { publisherName: 'Gabriel Fouraux', week: '27 de OUT - 2 de NOV, 2025', partTitle: 'Leitor', type: ParticipationType.LEITOR },
  { publisherName: 'Daniel Silva', week: '27 de OUT - 2 de NOV, 2025', partTitle: 'Oração Final', type: ParticipationType.ORACAO_FINAL },

  // SEMANA 3-9 DE NOVEMBRO | 2025
  { publisherName: 'Eliezer Rosa', week: '3-9 de NOV, 2025', partTitle: 'Presidente', type: ParticipationType.PRESIDENTE },
  { publisherName: 'Eliezer Rosa', week: '3-9 de NOV, 2025', partTitle: 'Oração Inicial', type: ParticipationType.ORACAO_INICIAL },
  { publisherName: 'Emerson Souza', week: '3-9 de NOV, 2025', partTitle: 'Uma história de amor verdadeiro', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Daniel Silva', week: '3-9 de NOV, 2025', partTitle: 'Joias espirituais', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Claudio Vieira', week: '3-9 de NOV, 2025', partTitle: 'Leitura da Bíblia', type: ParticipationType.TESOUROS, duration: 4 },
  { publisherName: 'Saymon Schultz', week: '3-9 de NOV, 2025', partTitle: 'Iniciando conversas', type: ParticipationType.MINISTERIO, duration: 3 },
  { publisherName: 'Maria de Lourdes', week: '3-9 de NOV, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Eryck Segall', week: '3-9 de NOV, 2025', partTitle: 'Cultivando o interesse', type: ParticipationType.MINISTERIO, duration: 4 },
  { publisherName: 'Vinícius Pessanha', week: '3-9 de NOV, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Felipe Oliveira', week: '3-9 de NOV, 2025', partTitle: 'Fazendo discípulos', type: ParticipationType.MINISTERIO, duration: 5 },
  { publisherName: 'Vitor Pessanha', week: '3-9 de NOV, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Diego Fontana', week: '3-9 de NOV, 2025', partTitle: '"A pessoa generosa será abençoada"', type: ParticipationType.VIDA_CRISTA, duration: 15 },
  { publisherName: 'José Luiz', week: '3-9 de NOV, 2025', partTitle: 'Dirigente', type: ParticipationType.DIRIGENTE, duration: 30 },
  { publisherName: 'Emerson Souza', week: '3-9 de NOV, 2025', partTitle: 'Leitor', type: ParticipationType.LEITOR },
  { publisherName: 'Eryck Segall', week: '3-9 de NOV, 2025', partTitle: 'Oração Final', type: ParticipationType.ORACAO_FINAL },

  // SEMANA 10-16 DE NOVEMBRO | 2025
  { publisherName: 'Renato Oliveira', week: '10-16 de NOV, 2025', partTitle: 'Presidente', type: ParticipationType.PRESIDENTE },
  { publisherName: 'Renato Oliveira', week: '10-16 de NOV, 2025', partTitle: 'Oração Inicial', type: ParticipationType.ORACAO_INICIAL },
  { publisherName: 'Patrick Oliveira', week: '10-16 de NOV, 2025', partTitle: 'A importância da beleza interior', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Alexsandro Lopes', week: '10-16 de NOV, 2025', partTitle: 'Joias espirituais', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Edmilson Pessanha', week: '10-16 de NOV, 2025', partTitle: 'Leitura da Bíblia', type: ParticipationType.TESOUROS, duration: 4 },
  { publisherName: 'Inêz Monteiro', week: '10-16 de NOV, 2025', partTitle: 'Iniciando conversas', type: ParticipationType.MINISTERIO, duration: 3 },
  { publisherName: 'Márcia Bragança', week: '10-16 de NOV, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Maria Izabel', week: '10-16 de NOV, 2025', partTitle: 'Iniciando conversas', type: ParticipationType.MINISTERIO, duration: 4 },
  { publisherName: 'Luciana Alves', week: '10-16 de NOV, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Antônio Miguel', week: '10-16 de NOV, 2025', partTitle: 'Discurso', type: ParticipationType.MINISTERIO, duration: 5 },
  { publisherName: 'Marcos Rogério', week: '10-16 de NOV, 2025', partTitle: 'Será que você seria um bom marido ou uma boa esposa?', type: ParticipationType.VIDA_CRISTA, duration: 7 },
  { publisherName: 'Domingos Oliveira', week: '10-16 de NOV, 2025', partTitle: 'Dirigente', type: ParticipationType.DIRIGENTE, duration: 30 },
  { publisherName: 'Eryck Segall', week: '10-16 de NOV, 2025', partTitle: 'Leitor', type: ParticipationType.LEITOR },
  { publisherName: 'Alexsandro Lopes', week: '10-16 de NOV, 2025', partTitle: 'Oração Final', type: ParticipationType.ORACAO_FINAL },

  // SEMANA 24-30 DE NOVEMBRO | 2025
  { publisherName: 'Diego Fontana', week: '24-30 de NOV, 2025', partTitle: 'Presidente', type: ParticipationType.PRESIDENTE },
  { publisherName: 'Diego Fontana', week: '24-30 de NOV, 2025', partTitle: 'Oração Inicial', type: ParticipationType.ORACAO_INICIAL },
  { publisherName: 'Edmilson Monteiro', week: '24-30 de NOV, 2025', partTitle: 'Esperança para os que estão ‘carregados de erro’', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Edmardo Queiroz', week: '24-30 de NOV, 2025', partTitle: 'Joias espirituais', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Saymon Schultz', week: '24-30 de NOV, 2025', partTitle: 'Leitura da Bíblia', type: ParticipationType.TESOUROS, duration: 4 },
  { publisherName: 'Samuel Almeida', week: '24-30 de NOV, 2025', partTitle: 'Iniciando conversas', type: ParticipationType.MINISTERIO, duration: 3 },
  { publisherName: 'Claudio Vieira', week: '24-30 de NOV, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Marcela Resmann', week: '24-30 de NOV, 2025', partTitle: 'Cultivando o interesse', type: ParticipationType.MINISTERIO, duration: 4 },
  { publisherName: 'Josyane Vieira', week: '24-30 de NOV, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Carlos Ramos', week: '24-30 de NOV, 2025', partTitle: 'Discurso', type: ParticipationType.MINISTERIO, duration: 5 },
  { publisherName: 'Felipe Oliveira', week: '24-30 de NOV, 2025', partTitle: 'Torne-se Amigo de Jeová — Jeová nos Perdoa', type: ParticipationType.VIDA_CRISTA, duration: 15 },
  { publisherName: 'Edmilson M', week: '24-30 de NOV, 2025', partTitle: 'Dirigente', type: ParticipationType.DIRIGENTE, duration: 30 },
  { publisherName: 'Antônio Nascimento', week: '24-30 de NOV, 2025', partTitle: 'Leitor', type: ParticipationType.LEITOR },
  { publisherName: 'Felipe Oliveira', week: '24-30 de NOV, 2025', partTitle: 'Oração Final', type: ParticipationType.ORACAO_FINAL },
  
  // SEMANA 4-10 DE NOVEMBRO | 2024
  { publisherName: 'Eliezer Rosa', week: '4-10 de NOV, 2024', partTitle: 'Presidente', type: ParticipationType.PRESIDENTE },
  { publisherName: 'Eliezer Rosa', week: '4-10 de NOV, 2024', partTitle: 'Oração Inicial', type: ParticipationType.ORACAO_INICIAL },
  { publisherName: 'Edmardo Queiroz', week: '4-10 de NOV, 2024', partTitle: 'Ele se lembra do seu pacto para sempre', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Marcos Vinícios', week: '4-10 de NOV, 2024', partTitle: 'Joias espirituais', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Samuel Almeida', week: '4-10 de NOV, 2024', partTitle: 'Leitura da Bíblia', type: ParticipationType.TESOUROS, duration: 4 },
  { publisherName: 'Rozelita Sales', week: '4-10 de NOV, 2024', partTitle: 'Iniciando conversas', type: ParticipationType.MINISTERIO, duration: 1 },
  { publisherName: 'Keyla Costa', week: '4-10 de NOV, 2024', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Yngrid França', week: '4-10 de NOV, 2024', partTitle: 'Iniciando conversas', type: ParticipationType.MINISTERIO, duration: 2 },
  { publisherName: 'Wanderleia Santos', week: '4-10 de NOV, 2024', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Suellen Correa', week: '4-10 de NOV, 2024', partTitle: 'Cultivando o interesse', type: ParticipationType.MINISTERIO, duration: 4 },
  { publisherName: 'Waleska Nascimento', week: '4-10 de NOV, 2024', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Tainá Reis', week: '4-10 de NOV, 2024', partTitle: 'Cultivando o interesse', type: ParticipationType.MINISTERIO, duration: 4 },
  { publisherName: 'Vitoria Emanuelle', week: '4-10 de NOV, 2024', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Marcos Rogério', week: '4-10 de NOV, 2024', partTitle: 'Demonstrações do nosso amor', type: ParticipationType.VIDA_CRISTA, duration: 15 },
  { publisherName: 'Renato Oliveira', week: '4-10 de NOV, 2024', partTitle: 'Dirigente', type: ParticipationType.DIRIGENTE, duration: 30 },
  { publisherName: 'Júnior Fouraux', week: '4-10 de NOV, 2024', partTitle: 'Leitor', type: ParticipationType.LEITOR },
  { publisherName: 'André Luiz', week: '4-10 de NOV, 2024', partTitle: 'Oração Final', type: ParticipationType.ORACAO_FINAL },

  // SEMANA 11-17 DE NOVEMBRO | 2024
  { publisherName: 'Domingos Oliveira', week: '11-17 de NOV, 2024', partTitle: 'Presidente', type: ParticipationType.PRESIDENTE },
  { publisherName: 'Domingos Oliveira', week: '11-17 de NOV, 2024', partTitle: 'Oração Inicial', type: ParticipationType.ORACAO_INICIAL },
  { publisherName: 'Renato Oliveira', week: '11-17 de NOV, 2024', partTitle: 'Esqueceram-se de Deus, seu Salvador', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Juberto Santos', week: '11-17 de NOV, 2024', partTitle: 'Joias espirituais', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'André Luiz', week: '11-17 de NOV, 2024', partTitle: 'Leitura da Bíblia', type: ParticipationType.TESOUROS, duration: 4 },
  { publisherName: 'Emerson Souza', week: '11-17 de NOV, 2024', partTitle: 'Simplicidade — O que Jesus fez', type: ParticipationType.MINISTERIO, duration: 7 },
  { publisherName: 'Eliezer Rosa', week: '11-17 de NOV, 2024', partTitle: 'Simplicidade — Imite Jesus', type: ParticipationType.MINISTERIO, duration: 8 },
  { publisherName: 'Israel Vieira', week: '11-17 de NOV, 2024', partTitle: 'Necessidades locais', type: ParticipationType.VIDA_CRISTA, duration: 15 },
  { publisherName: 'Israel Vieira', week: '11-17 de NOV, 2024', partTitle: 'Oração Final', type: ParticipationType.ORACAO_FINAL },

  // SEMANA 18-24 DE NOVEMBRO | 2024
  { publisherName: 'Marcos Vinícios', week: '18-24 de NOV, 2024', partTitle: 'Presidente', type: ParticipationType.PRESIDENTE },
  { publisherName: 'Marcos Vinícios', week: '18-24 de NOV, 2024', partTitle: 'Oração Inicial', type: ParticipationType.ORACAO_INICIAL },
  { publisherName: 'Eliezer Rosa', week: '18-24 de NOV, 2024', partTitle: 'Agradeçam a Jeová, pois ele é bom', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Edmardo Queiroz', week: '18-24 de NOV, 2024', partTitle: 'Joias espirituais', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Saymon Schultz', week: '18-24 de NOV, 2024', partTitle: 'Leitura da Bíblia', type: ParticipationType.TESOUROS, duration: 4 },
  { publisherName: 'Saniyuriss Reis', week: '18-24 de NOV, 2024', partTitle: 'Iniciando conversas', type: ParticipationType.MINISTERIO, duration: 3 },
  { publisherName: 'Julianne Pereira', week: '18-24 de NOV, 2024', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Josyane Vieira', week: '18-24 de NOV, 2024', partTitle: 'Cultivando o interesse', type: ParticipationType.MINISTERIO, duration: 4 },
  { publisherName: 'Jacyra Eugênio', week: '18-24 de NOV, 2024', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Juberto Santos', week: '18-24 de NOV, 2024', partTitle: 'Discurso', type: ParticipationType.MINISTERIO, duration: 5 },
  { publisherName: 'José Luiz Fouraux', week: '18-24 de NOV, 2024', partTitle: 'Cantamos para agradecer a Jeová', type: ParticipationType.VIDA_CRISTA, duration: 15 },
  { publisherName: 'Diego Fontana', week: '18-24 de NOV, 2024', partTitle: 'Dirigente', type: ParticipationType.DIRIGENTE, duration: 30 },
  { publisherName: 'Carlos Ramos', week: '18-24 de NOV, 2024', partTitle: 'Leitor', type: ParticipationType.LEITOR },
  { publisherName: 'Juberto Santos', week: '18-24 de NOV, 2024', partTitle: 'Oração Final', type: ParticipationType.ORACAO_FINAL },
  
  // DEZEMBRO 2024
  { publisherName: 'Marcos Rogério', week: '25 de NOV - 1 de DEZ, 2024', partTitle: 'Presidente', type: ParticipationType.PRESIDENTE },
  { publisherName: 'Marcos Rogério', week: '25 de NOV - 1 de DEZ, 2024', partTitle: 'Oração Inicial', type: ParticipationType.ORACAO_INICIAL },
  { publisherName: 'Domingos Oliveira', week: '25 de NOV - 1 de DEZ, 2024', partTitle: 'Apoie o Rei Jesus!', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Samuel Almeida', week: '25 de NOV - 1 de DEZ, 2024', partTitle: 'Joias espirituais', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Hidelmar Amorim', week: '25 de NOV - 1 de DEZ, 2024', partTitle: 'Leitura da Bíblia', type: ParticipationType.TESOUROS, duration: 4 },
  { publisherName: 'Sandra Duarte', week: '25 de NOV - 1 de DEZ, 2024', partTitle: 'Iniciando conversas', type: ParticipationType.MINISTERIO, duration: 2 },
  { publisherName: 'Olívia Porto', week: '25 de NOV - 1 de DEZ, 2024', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Solange Telles', week: '25 de NOV - 1 de DEZ, 2024', partTitle: 'Explicando suas crenças', type: ParticipationType.MINISTERIO, duration: 5 },
  { publisherName: 'Ana Paula Oliveira', week: '25 de NOV - 1 de DEZ, 2024', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Edna Costa', week: '25 de NOV - 1 de DEZ, 2024', partTitle: 'Fazendo discípulos', type: ParticipationType.MINISTERIO, duration: 5 },
  { publisherName: 'Marilene Queiroz', week: '25 de NOV - 1 de DEZ, 2024', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Diego Fontana', week: '25 de NOV - 1 de DEZ, 2024', partTitle: 'Como podemos apoiar o Reino de Deus de todo o coração?', type: ParticipationType.VIDA_CRISTA, duration: 15 },
  { publisherName: 'Israel Vieira', week: '25 de NOV - 1 de DEZ, 2024', partTitle: 'Dirigente', type: ParticipationType.DIRIGENTE, duration: 30 },
  { publisherName: 'Vitor Ramos', week: '25 de NOV - 1 de DEZ, 2024', partTitle: 'Leitor', type: ParticipationType.LEITOR },
  { publisherName: 'Antônio Miguel', week: '25 de NOV - 1 de DEZ, 2024', partTitle: 'Oração Final', type: ParticipationType.ORACAO_FINAL },

  { publisherName: 'Diego Fontana', week: '2-8 de DEZ, 2024', partTitle: 'Presidente', type: ParticipationType.PRESIDENTE },
  { publisherName: 'Diego Fontana', week: '2-8 de DEZ, 2024', partTitle: 'Oração Inicial', type: ParticipationType.ORACAO_INICIAL },
  { publisherName: 'Marcos Vinícios', week: '2-8 de DEZ, 2024', partTitle: 'Como vou retribuir a Jeová?', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Alexsandro Lopes', week: '2-8 de DEZ, 2024', partTitle: 'Joias espirituais', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Emerson França', week: '2-8 de DEZ, 2024', partTitle: 'Leitura da Bíblia', type: ParticipationType.TESOUROS, duration: 4 },
  { publisherName: 'Samuel Almeida', week: '2-8 de DEZ, 2024', partTitle: 'Franqueza — O que Jesus fez', type: ParticipationType.MINISTERIO, duration: 7 },
  { publisherName: 'Israel Vieira', week: '2-8 de DEZ, 2024', partTitle: 'Franqueza — Imite Jesus', type: ParticipationType.MINISTERIO, duration: 8 },
  { publisherName: 'Marcos Rogério', week: '2-8 de DEZ, 2024', partTitle: 'Necessidades locais', type: ParticipationType.VIDA_CRISTA, duration: 15 },
  { publisherName: 'Domingos O', week: '2-8 de DEZ, 2024', partTitle: 'Dirigente', type: ParticipationType.DIRIGENTE, duration: 30 },
  { publisherName: 'Getúlio Rastoldo', week: '2-8 de DEZ, 2024', partTitle: 'Leitor', type: ParticipationType.LEITOR },
  { publisherName: 'Mário Porto', week: '2-8 de DEZ, 2024', partTitle: 'Oração Final', type: ParticipationType.ORACAO_FINAL },
  
  { publisherName: 'Israel Vieira', week: '9-15 de DEZ, 2024', partTitle: 'Presidente', type: ParticipationType.PRESIDENTE },
  { publisherName: 'Israel Vieira', week: '9-15 de DEZ, 2024', partTitle: 'Oração Inicial', type: ParticipationType.ORACAO_INICIAL },
  { publisherName: 'Alexsandro Lopes', week: '9-15 de DEZ, 2024', partTitle: '"Como um jovem pode manter puro o seu caminho?"', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Júnior Fouraux', week: '9-15 de DEZ, 2024', partTitle: 'Joias espirituais', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Antônio Nascimento', week: '9-15 de DEZ, 2024', partTitle: 'Leitura da Bíblia', type: ParticipationType.TESOUROS, duration: 4 },
  { publisherName: 'Eliana Souza', week: '9-15 de DEZ, 2024', partTitle: 'Iniciando conversas', type: ParticipationType.MINISTERIO, duration: 3 },
  { publisherName: 'Wanderleia Santos', week: '9-15 de DEZ, 2024', partTitle: 'Cultivando o interesse', type: ParticipationType.MINISTERIO, duration: 4 },
  { publisherName: 'Elza Elena', week: '9-15 de DEZ, 2024', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'José Luiz Fouraux', week: '9-15 de DEZ, 2024', partTitle: 'Discurso', type: ParticipationType.MINISTERIO, duration: 5 },
  { publisherName: 'Marcos Rogério', week: '9-15 de DEZ, 2024', partTitle: 'Dirigente', type: ParticipationType.DIRIGENTE, duration: 29 },
  { publisherName: 'Gabriel Camilo', week: '9-15 de DEZ, 2024', partTitle: 'Leitor', type: ParticipationType.LEITOR },
  { publisherName: 'Júnior Fouraux', week: '9-15 de DEZ, 2024', partTitle: 'Oração Final', type: ParticipationType.ORACAO_FINAL },

  { publisherName: 'Edmardo Queiroz', week: '16-22 de DEZ, 2024', partTitle: 'Presidente', type: ParticipationType.PRESIDENTE },
  { publisherName: 'Edmardo Queiroz', week: '16-22 de DEZ, 2024', partTitle: 'Oração Inicial', type: ParticipationType.ORACAO_INICIAL },
  { publisherName: 'Juberto Santos', week: '16-22 de DEZ, 2024', partTitle: 'Como perseverar diante de dificuldades', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'José Luiz Fouraux', week: '16-22 de DEZ, 2024', partTitle: 'Joias espirituais', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Daniel Silva', week: '16-22 de DEZ, 2024', partTitle: 'Leitura da Bíblia', type: ParticipationType.TESOUROS, duration: 4 },
  { publisherName: 'Terezinha Oliveira', week: '16-22 de DEZ, 2024', partTitle: 'Iniciando conversas', type: ParticipationType.MINISTERIO, duration: 3 },
  { publisherName: 'Débora Cristine', week: '16-22 de DEZ, 2024', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Vitoria Emanuelle', week: '16-22 de DEZ, 2024', partTitle: 'Cultivando o interesse', type: ParticipationType.MINISTERIO, duration: 4 },
  { publisherName: 'Dayse Campos', week: '16-22 de DEZ, 2024', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Waleska Nascimento', week: '16-22 de DEZ, 2024', partTitle: 'Explicando suas crenças', type: ParticipationType.MINISTERIO, duration: 5 },
  { publisherName: 'Ágatha do Nascimento', week: '16-22 de DEZ, 2024', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Renato Oliveira', week: '16-22 de DEZ, 2024', partTitle: 'Jeová nos ajuda a perseverar', type: ParticipationType.VIDA_CRISTA, duration: 15 },
  { publisherName: 'Marcos Vinícios', week: '16-22 de DEZ, 2024', partTitle: 'Dirigente', type: ParticipationType.DIRIGENTE, duration: 30 },
  { publisherName: 'Felipe Oliveira', week: '16-22 de DEZ, 2024', partTitle: 'Leitor', type: ParticipationType.LEITOR },
  { publisherName: 'Renato Oliveira', week: '16-22 de DEZ, 2024', partTitle: 'Oração Final', type: ParticipationType.ORACAO_FINAL },

  { publisherName: 'Renato Oliveira', week: '23-29 de DEZ, 2024', partTitle: 'Presidente', type: ParticipationType.PRESIDENTE },
  { publisherName: 'Renato Oliveira', week: '23-29 de DEZ, 2024', partTitle: 'Oração Inicial', type: ParticipationType.ORACAO_INICIAL },
  { publisherName: 'Marcos Rogério', week: '23-29 de DEZ, 2024', partTitle: 'Como evitar sofrimento desnecessário', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Emerson Souza', week: '23-29 de DEZ, 2024', partTitle: 'Joias espirituais', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'João Paulo', week: '23-29 de DEZ, 2024', partTitle: 'Leitura da Bíblia', type: ParticipationType.TESOUROS, duration: 4 },
  { publisherName: 'Ana Paula', week: '23-29 de DEZ, 2024', partTitle: 'Iniciando conversas', type: ParticipationType.MINISTERIO, duration: 3 },
  { publisherName: 'Tainá Reis', week: '23-29 de DEZ, 2024', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Ariane Bello', week: '23-29 de DEZ, 2024', partTitle: 'Cultivando o interesse', type: ParticipationType.MINISTERIO, duration: 4 },
  { publisherName: 'Ágatha Nascimento', week: '23-29 de DEZ, 2024', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Érika Segall', week: '23-29 de DEZ, 2024', partTitle: 'Fazendo discípulos', type: ParticipationType.MINISTERIO, duration: 5 },
  { publisherName: 'Terezinha Oliveira', week: '23-29 de DEZ, 2024', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Eliezer Rosa', week: '23-29 de DEZ, 2024', partTitle: 'Não deixe o dinheiro fazer você sofrer desnecessariamente', type: ParticipationType.VIDA_CRISTA, duration: 15 },
  { publisherName: 'Edmardo Queiroz', week: '23-29 de DEZ, 2024', partTitle: 'Dirigente', type: ParticipationType.DIRIGENTE, duration: 30 },
  { publisherName: 'Erick José', week: '23-29 de DEZ, 2024', partTitle: 'Leitor', type: ParticipationType.LEITOR },
  { publisherName: 'Erick José', week: '23-29 de DEZ, 2024', partTitle: 'Oração Final', type: ParticipationType.ORACAO_FINAL },

  { publisherName: 'Eliezer Rosa', week: '30 de DEZ, 2024 - 5 de JAN, 2025', partTitle: 'Presidente', type: ParticipationType.PRESIDENTE },
  { publisherName: 'Eliezer Rosa', week: '30 de DEZ, 2024 - 5 de JAN, 2025', partTitle: 'Oração Inicial', type: ParticipationType.ORACAO_INICIAL },
  { publisherName: 'Diego Fontana', week: '30 de DEZ, 2024 - 5 de JAN, 2025', partTitle: 'Eles semearam com lágrimas, mas colheram com alegria', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Alexsandro Lopes', week: '30 de DEZ, 2024 - 5 de JAN, 2025', partTitle: 'Joias espirituais', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Gabriel Fouraux', week: '30 de DEZ, 2024 - 5 de JAN, 2025', partTitle: 'Leitura da Bíblia', type: ParticipationType.TESOUROS, duration: 4 },
  { publisherName: 'Ágatha Nascimento', week: '30 de DEZ, 2024 - 5 de JAN, 2025', partTitle: 'Iniciando conversas', type: ParticipationType.MINISTERIO, duration: 3 },
  { publisherName: 'Malena Colangero', week: '30 de DEZ, 2024 - 5 de JAN, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Auxiliadora Valéria', week: '30 de DEZ, 2024 - 5 de JAN, 2025', partTitle: 'Cultivando o interesse', type: ParticipationType.MINISTERIO, duration: 4 },
  { publisherName: 'Michele Camillo', week: '30 de DEZ, 2024 - 5 de JAN, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Eliana Souza', week: '30 de DEZ, 2024 - 5 de JAN, 2025', partTitle: 'Fazendo discípulos', type: ParticipationType.MINISTERIO, duration: 5 },
  { publisherName: 'Neuza Campanha', week: '30 de DEZ, 2024 - 5 de JAN, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Juberto Santos', week: '30 de DEZ, 2024 - 5 de JAN, 2025', partTitle: 'Alegre-se com as promessas de Deus', type: ParticipationType.VIDA_CRISTA, duration: 15 },
  { publisherName: 'Renato Oliveira', week: '30 de DEZ, 2024 - 5 de JAN, 2025', partTitle: 'Dirigente', type: ParticipationType.DIRIGENTE, duration: 30 },
  { publisherName: 'Victor Correa', week: '30 de DEZ, 2024 - 5 de JAN, 2025', partTitle: 'Leitor', type: ParticipationType.LEITOR },
  { publisherName: 'Alexsandro Lopes', week: '30 de DEZ, 2024 - 5 de JAN, 2025', partTitle: 'Oração Final', type: ParticipationType.ORACAO_FINAL },

  // JANEIRO 2025
  { publisherName: 'Israel Vieira', week: '13-19 de JAN, 2025', partTitle: 'Presidente', type: ParticipationType.PRESIDENTE },
  { publisherName: 'Israel Vieira', week: '13-19 de JAN, 2025', partTitle: 'Oração Inicial', type: ParticipationType.ORACAO_INICIAL },
  { publisherName: 'José Luiz Fouraux', week: '13-19 de JAN, 2025', partTitle: '"Nosso Senhor é maior do que todos os outros deuses"', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Juberto Santos', week: '13-19 de JAN, 2025', partTitle: 'Joias espirituais', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Gustavo Rangel', week: '13-19 de JAN, 2025', partTitle: 'Leitura da Bíblia', type: ParticipationType.TESOUROS, duration: 4 },
  { publisherName: 'Elza Elena', week: '13-19 de JAN, 2025', partTitle: 'Iniciando conversas', type: ParticipationType.MINISTERIO, duration: 3 },
  { publisherName: 'Priscila', week: '13-19 de JAN, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Dione Guimarães', week: '13-19 de JAN, 2025', partTitle: 'Cultivando o interesse', type: ParticipationType.MINISTERIO, duration: 4 },
  { publisherName: 'Olívia Maria', week: '13-19 de JAN, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Edna Costa', week: '13-19 de JAN, 2025', partTitle: 'Explicando suas crenças', type: ParticipationType.MINISTERIO, duration: 5 },
  { publisherName: 'Raquel Oliveira', week: '13-19 de JAN, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Marcos Rogério', week: '13-19 de JAN, 2025', partTitle: 'Necessidades locais', type: ParticipationType.VIDA_CRISTA, duration: 15 },
  { publisherName: 'Eliezer Rosa', week: '13-19 de JAN, 2025', partTitle: 'Dirigente', type: ParticipationType.DIRIGENTE, duration: 30 },
  { publisherName: 'Patrick de Oliveira', week: '13-19 de JAN, 2025', partTitle: 'Leitor', type: ParticipationType.LEITOR },
  { publisherName: 'Patrick de Oliveira', week: '13-19 de JAN, 2025', partTitle: 'Oração Final', type: ParticipationType.ORACAO_FINAL },
  
  { publisherName: 'Diego Fontana', week: '20-26 de JAN, 2025', partTitle: 'Presidente', type: ParticipationType.PRESIDENTE },
  { publisherName: 'Diego Fontana', week: '20-26 de JAN, 2025', partTitle: 'Oração Inicial', type: ParticipationType.ORACAO_INICIAL },
  { publisherName: 'Marcos Vinícios', week: '20-26 de JAN, 2025', partTitle: 'O nervosismo não precisa impedir você de participar nas reuniões', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'José Luiz Fouraux', week: '20-26 de JAN, 2025', partTitle: 'Joias espirituais', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Gérson Santos', week: '20-26 de JAN, 2025', partTitle: 'Leitura da Bíblia', type: ParticipationType.TESOUROS, duration: 4 },
  { publisherName: 'Deusedir Amorim', week: '20-26 de JAN, 2025', partTitle: 'Iniciando conversas', type: ParticipationType.MINISTERIO, duration: 3 },
  { publisherName: 'Suellen Correa', week: '20-26 de JAN, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Débora Cristine', week: '20-26 de JAN, 2025', partTitle: 'Fazendo discípulos', type: ParticipationType.MINISTERIO, duration: 4 },
  { publisherName: 'Rozelita Sales', week: '20-26 de JAN, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Júnior Fouraux', week: '20-26 de JAN, 2025', partTitle: 'Discurso', type: ParticipationType.MINISTERIO, duration: 5 },
  { publisherName: 'Emerson Souza', week: '20-26 de JAN, 2025', partTitle: 'Você pode se sair bem no ministério apesar da timidez', type: ParticipationType.VIDA_CRISTA, duration: 15 },
  { publisherName: 'Domingos Oliveira', week: '20-26 de JAN, 2025', partTitle: 'Dirigente', type: ParticipationType.DIRIGENTE, duration: 30 },
  { publisherName: 'André Luiz', week: '20-26 de JAN, 2025', partTitle: 'Leitor', type: ParticipationType.LEITOR },
  { publisherName: 'Mário Porto', week: '20-26 de JAN, 2025', partTitle: 'Oração Final', type: ParticipationType.ORACAO_FINAL },
  
  { publisherName: 'Edmardo Queiroz', week: '27 de JAN - 2 de FEV, 2025', partTitle: 'Presidente', type: ParticipationType.PRESIDENTE },
  { publisherName: 'Edmardo Queiroz', week: '27 de JAN - 2 de FEV, 2025', partTitle: 'Oração Inicial', type: ParticipationType.ORACAO_INICIAL },
  { publisherName: 'Domingos Oliveira', week: '27 de JAN - 2 de FEV, 2025', partTitle: 'Aja de acordo com suas súplicas por ajuda', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Júnior Fouraux', week: '27 de JAN - 2 de FEV, 2025', partTitle: 'Joias espirituais', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'João Paulo', week: '27 de JAN - 2 de FEV, 2025', partTitle: 'Leitura da Bíblia', type: ParticipationType.TESOUROS, duration: 4 },
  { publisherName: 'Daniele Santos', week: '27 de JAN - 2 de FEV, 2025', partTitle: 'Iniciando conversas', type: ParticipationType.MINISTERIO, duration: 4 },
  { publisherName: 'Yngrid França', week: '27 de JAN - 2 de FEV, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Edlena Longo', week: '27 de JAN - 2 de FEV, 2025', partTitle: 'Cultivando o interesse', type: ParticipationType.MINISTERIO, duration: 3 },
  { publisherName: 'Wanderleia Santos', week: '27 de JAN - 2 de FEV, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Erica Vaz', week: '27 de JAN - 2 de FEV, 2025', partTitle: 'Explicando suas crenças', type: ParticipationType.MINISTERIO, duration: 5 },
  { publisherName: 'Waleska Nascimento', week: '27 de JAN - 2 de FEV, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Marcos Rogério', week: '27 de JAN - 2 de FEV, 2025', partTitle: 'Esteja preparado para situações que possam exigir cuidados médicos', type: ParticipationType.VIDA_CRISTA, duration: 10 },
  { publisherName: 'Israel Vieira', week: '27 de JAN - 2 de FEV, 2025', partTitle: 'Dirigente', type: ParticipationType.DIRIGENTE, duration: 29 },
  { publisherName: 'Samuel Almeida', week: '27 de JAN - 2 de FEV, 2025', partTitle: 'Leitor', type: ParticipationType.LEITOR },
  { publisherName: 'Samuel Almeida', week: '27 de JAN - 2 de FEV, 2025', partTitle: 'Oração Final', type: ParticipationType.ORACAO_FINAL },

  // FEVEREIRO 2025
  { publisherName: 'Marcos Vinícios', week: '3-9 de FEV, 2025', partTitle: 'Presidente', type: ParticipationType.PRESIDENTE },
  { publisherName: 'Marcos Vinícios', week: '3-9 de FEV, 2025', partTitle: 'Oração Inicial', type: ParticipationType.ORACAO_INICIAL },
  { publisherName: 'Alexsandro Lopes', week: '3-9 de FEV, 2025', partTitle: '"Feliz o povo cujo Deus é Jeová!"', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'José Luiz Fouraux', week: '3-9 de FEV, 2025', partTitle: 'Joias espirituais', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Victor Correa', week: '3-9 de FEV, 2025', partTitle: 'Leitura da Bíblia', type: ParticipationType.TESOUROS, duration: 4 },
  { publisherName: 'André Luiz', week: '3-9 de FEV, 2025', partTitle: 'Iniciando conversas', type: ParticipationType.MINISTERIO, duration: 4 },
  { publisherName: 'Raquel Oliveira', week: '3-9 de FEV, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Eryck José', week: '3-9 de FEV, 2025', partTitle: 'Cultivando o interesse', type: ParticipationType.MINISTERIO, duration: 4 },
  { publisherName: 'Felipe de Oliveira', week: '3-9 de FEV, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Emerson França', week: '3-9 de FEV, 2025', partTitle: 'Discurso', type: ParticipationType.MINISTERIO, duration: 4 },
  { publisherName: 'Samuel Almeida', week: '3-9 de FEV, 2025', partTitle: 'Jeová quer que você seja feliz', type: ParticipationType.VIDA_CRISTA, duration: 10 },
  { publisherName: 'Diego Fontana', week: '3-9 de FEV, 2025', partTitle: 'Necessidades locais', type: ParticipationType.VIDA_CRISTA, duration: 5 },
  { publisherName: 'Renato Oliveira', week: '3-9 de FEV, 2025', partTitle: 'Dirigente', type: ParticipationType.DIRIGENTE, duration: 30 },
  { publisherName: 'Gabriel Fouraux', week: '3-9 de FEV, 2025', partTitle: 'Leitor', type: ParticipationType.LEITOR },
  { publisherName: 'Antônio Nascimento', week: '3-9 de FEV, 2025', partTitle: 'Oração Final', type: ParticipationType.ORACAO_FINAL },
  
  { publisherName: 'Domingos Oliveira', week: '10-16 de FEV, 2025', partTitle: 'Presidente', type: ParticipationType.PRESIDENTE },
  { publisherName: 'Domingos Oliveira', week: '10-16 de FEV, 2025', partTitle: 'Oração Inicial', type: ParticipationType.ORACAO_INICIAL },
  { publisherName: 'Patrick Oliveira', week: '10-16 de FEV, 2025', partTitle: 'Temos muitos motivos para louvar a Jah', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Edmardo Queiroz', week: '10-16 de FEV, 2025', partTitle: 'Joias espirituais', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Getúlio Rastoldo', week: '10-16 de FEV, 2025', partTitle: 'Leitura da Bíblia', type: ParticipationType.TESOUROS, duration: 4 },
  { publisherName: 'Gustavo Rangel', week: '10-16 de FEV, 2025', partTitle: 'Iniciando conversas', type: ParticipationType.MINISTERIO, duration: 3 },
  { publisherName: 'Isabelle Silva', week: '10-16 de FEV, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Vitor Ramos', week: '10-16 de FEV, 2025', partTitle: 'Iniciando conversas', type: ParticipationType.MINISTERIO, duration: 4 },
  { publisherName: 'Diego Ramos', week: '10-16 de FEV, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Alexsandro Lopes', week: '10-16 de FEV, 2025', partTitle: 'Discurso', type: ParticipationType.MINISTERIO, duration: 5 },
  { publisherName: 'Eliezer Rosa', week: '10-16 de FEV, 2025', partTitle: 'Relatório anual de serviço', type: ParticipationType.VIDA_CRISTA, duration: 15 },
  { publisherName: 'Fernando Pessoa', week: '10-16 de FEV, 2025', partTitle: 'Dirigente', type: ParticipationType.DIRIGENTE, duration: 30 },
  { publisherName: 'Carlos Ramos', week: '10-16 de FEV, 2025', partTitle: 'Leitor', type: ParticipationType.LEITOR },
  { publisherName: 'Antônio Miguel', week: '10-16 de FEV, 2025', partTitle: 'Oração Final', type: ParticipationType.ORACAO_FINAL },

  { publisherName: 'Renato Oliveira', week: '17-23 de FEV, 2025', partTitle: 'Presidente', type: ParticipationType.PRESIDENTE },
  { publisherName: 'Renato Oliveira', week: '17-23 de FEV, 2025', partTitle: 'Oração Inicial', type: ParticipationType.ORACAO_INICIAL },
  { publisherName: 'José Luiz Fouraux', week: '17-23 de FEV, 2025', partTitle: 'Jovens — Quem vocês vão escutar?', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Júnior Fouraux', week: '17-23 de FEV, 2025', partTitle: 'Joias espirituais', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Carlos Ramos', week: '17-23 de FEV, 2025', partTitle: 'Leitura da Bíblia', type: ParticipationType.TESOUROS, duration: 4 },
  { publisherName: 'Daniele Santos', week: '17-23 de FEV, 2025', partTitle: 'Iniciando conversas', type: ParticipationType.MINISTERIO, duration: 2 },
  { publisherName: 'Josyane', week: '17-23 de FEV, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Keylla Costa', week: '17-23 de FEV, 2025', partTitle: 'Iniciando conversas', type: ParticipationType.MINISTERIO, duration: 2 },
  { publisherName: 'Edna', week: '17-23 de FEV, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Márcia Bragança', week: '17-23 de FEV, 2025', partTitle: 'Cultivando o interesse', type: ParticipationType.MINISTERIO, duration: 2 },
  { publisherName: 'Neuza', week: '17-23 de FEV, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Beatriz Pessoa', week: '17-23 de FEV, 2025', partTitle: 'Fazendo discípulos', type: ParticipationType.MINISTERIO, duration: 5 },
  { publisherName: 'Maria Izabel', week: '17-23 de FEV, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Marcos Vinícios', week: '17-23 de FEV, 2025', partTitle: 'Dirigente', type: ParticipationType.DIRIGENTE, duration: 30 },
  { publisherName: 'Daniel Silva', week: '17-23 de FEV, 2025', partTitle: 'Leitor', type: ParticipationType.LEITOR },
  { publisherName: 'Israel Vieira', week: '17-23 de FEV, 2025', partTitle: 'Oração Final', type: ParticipationType.ORACAO_FINAL },

  { publisherName: 'Diego Fontana', week: '24 de FEV - 2 de MAR, 2025', partTitle: 'Presidente', type: ParticipationType.PRESIDENTE },
  { publisherName: 'Diego Fontana', week: '24 de FEV - 2 de MAR, 2025', partTitle: 'Oração Inicial', type: ParticipationType.ORACAO_INICIAL },
  { publisherName: 'Eliezer Rosa', week: '24 de FEV - 2 de MAR, 2025', partTitle: 'Por que se dedicar ao seu estudo pessoal?', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Emerson Souza', week: '24 de FEV - 2 de MAR, 2025', partTitle: 'Joias espirituais', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Felipe de Oliveira', week: '24 de FEV - 2 de MAR, 2025', partTitle: 'Leitura da Bíblia', type: ParticipationType.TESOUROS, duration: 4 },
  { publisherName: 'Larissa Queiroz', week: '24 de FEV - 2 de MAR, 2025', partTitle: 'Iniciando conversas', type: ParticipationType.MINISTERIO, duration: 4 },
  { publisherName: 'Suellen Correa', week: '24 de FEV - 2 de MAR, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Laramara Rosa', week: '24 de FEV - 2 de MAR, 2025', partTitle: 'Cultivando o interesse', type: ParticipationType.MINISTERIO, duration: 3 },
  { publisherName: 'Waleska Nascimento', week: '24 de FEV - 2 de MAR, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Samuel Almeida', week: '24 de FEV - 2 de MAR, 2025', partTitle: 'Discurso', type: ParticipationType.MINISTERIO, duration: 5 },
  { publisherName: 'Marcos Rogério', week: '24 de FEV - 2 de MAR, 2025', partTitle: 'Você é um caçador de tesouros?', type: ParticipationType.VIDA_CRISTA, duration: 15 },
  { publisherName: 'Domingos Oliveira', week: '24 de FEV - 2 de MAR, 2025', partTitle: 'Dirigente', type: ParticipationType.DIRIGENTE, duration: 30 },
  { publisherName: 'Alexsandro Lopes', week: '24 de FEV - 2 de MAR, 2025', partTitle: 'Leitor', type: ParticipationType.LEITOR },
  { publisherName: 'Carlos Ramos', week: '24 de FEV - 2 de MAR, 2025', partTitle: 'Oração Final', type: ParticipationType.ORACAO_FINAL },
  
  // DEZEMBRO 2025 (Novas Pautas)
  { publisherName: 'Marcos Vinícios', week: '1-7 de DEZ, 2025', partTitle: 'Presidente', type: ParticipationType.PRESIDENTE },
  { publisherName: 'Marcos Vinícios', week: '1-7 de DEZ, 2025', partTitle: 'Oração Inicial', type: ParticipationType.ORACAO_INICIAL },
  { publisherName: 'Renato Oliveira', week: '1-7 de DEZ, 2025', partTitle: 'Jeová merecia e esperava obediência do seu povo', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'José Luiz Fouraux', week: '1-7 de DEZ, 2025', partTitle: 'Joias espirituais', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Gérson Santos', week: '1-7 de DEZ, 2025', partTitle: 'Leitura da Bíblia', type: ParticipationType.TESOUROS, duration: 4 },
  { publisherName: 'Yngrid França', week: '1-7 de DEZ, 2025', partTitle: 'Iniciando conversas', type: ParticipationType.MINISTERIO, duration: 3 },
  { publisherName: 'Keyla Costa', week: '1-7 de DEZ, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Jacyra Eugênio', week: '1-7 de DEZ, 2025', partTitle: 'Cultivando o interesse', type: ParticipationType.MINISTERIO, duration: 4 },
  { publisherName: 'Vitoria Emanuelle', week: '1-7 de DEZ, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Ana Paula Oliveira', week: '1-7 de DEZ, 2025', partTitle: 'Fazendo discípulos', type: ParticipationType.MINISTERIO, duration: 5 },
  { publisherName: 'Ágatha Nascimento', week: '1-7 de DEZ, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Edmardo Queiroz', week: '1-7 de DEZ, 2025', partTitle: 'Necessidades locais', type: ParticipationType.VIDA_CRISTA, duration: 15 },
  { publisherName: 'Israel Vieira', week: '1-7 de DEZ, 2025', partTitle: 'Dirigente', type: ParticipationType.DIRIGENTE, duration: 30 },
  { publisherName: 'Júnior Fouraux', week: '1-7 de DEZ, 2025', partTitle: 'Leitor', type: ParticipationType.LEITOR },
  { publisherName: 'André Luiz', week: '1-7 de DEZ, 2025', partTitle: 'Oração Final', type: ParticipationType.ORACAO_FINAL },

  { publisherName: 'Diego Fontana', week: '8-14 de DEZ, 2025', partTitle: 'Presidente', type: ParticipationType.PRESIDENTE },
  { publisherName: 'Diego Fontana', week: '8-14 de DEZ, 2025', partTitle: 'Oração Inicial', type: ParticipationType.ORACAO_INICIAL },
  { publisherName: 'Emerson Souza', week: '8-14 de DEZ, 2025', partTitle: '"Aqui estou! Envia-me!"', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Edmilson Monteiro', week: '8-14 de DEZ, 2025', partTitle: 'Joias espirituais', type: ParticipationType.TESOUROS, duration: 10 },
  { publisherName: 'Vitor Correa', week: '8-14 de DEZ, 2025', partTitle: 'Leitura da Bíblia', type: ParticipationType.TESOUROS, duration: 4 },
  { publisherName: 'Suellen Correa', week: '8-14 de DEZ, 2025', partTitle: 'Iniciando conversas', type: ParticipationType.MINISTERIO, duration: 3 },
  { publisherName: 'Julianne Cravo Figueredo', week: '8-14 de DEZ, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Marilene Queiroz', week: '8-14 de DEZ, 2025', partTitle: 'Cultivando o interesse', type: ParticipationType.MINISTERIO, duration: 4 },
  { publisherName: 'Terezinha Oliveira', week: '8-14 de DEZ, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Daniel Silva', week: '8-14 de DEZ, 2025', partTitle: 'Cultivando o interesse', type: ParticipationType.MINISTERIO, duration: 5 },
  { publisherName: 'Samuel Almeida', week: '8-14 de DEZ, 2025', partTitle: 'Ajudante', type: ParticipationType.AJUDANTE },
  { publisherName: 'Marcos Rogério', week: '8-14 de DEZ, 2025', partTitle: 'Pregação de casa em casa — nossa marca registrada', type: ParticipationType.VIDA_CRISTA, duration: 15 },
  { publisherName: 'João Marcos P. Costa (SC)', week: '8-14 de DEZ, 2025', partTitle: 'Amor - O perfeito vínculo de união', type: ParticipationType.VIDA_CRISTA },
  { publisherName: 'João Marcos P. Costa (SC)', week: '8-14 de DEZ, 2025', partTitle: 'Oração Final', type: ParticipationType.ORACAO_FINAL },
];

export const initialParticipations: Participation[] = rawParticipations.map(p => ({
    ...p,
    id: generateUUID(),
    date: calculatePartDate(p.week),
}));